### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by collectVood** [alexkroh/rcon_py#1]
Is this websocket based rcon for rust or source?

**Comment by collectVood** [comment]
Also is this written in python 2?

**Comment by alexkroh** [comment]
For Rust, and written in python 2.
It should be easy to extend.
Apologies for any bugs. It was a brief project that I no longer maintain.

**Comment by collectVood** [comment]
Hey thanks for the quick answer. I will definetly have a look, is it using websockets or source though?

**Comment by collectVood** [comment]
Im trying to make a discord Bot which automatically sends the messages from the server into discord. Discord isnt the problem here just have no experience with websockets.

**Comment by alexkroh** [comment]
It uses standard sockets https://docs.python.org/2/library/socket.html
I'm afraid I have no experience with websockets either.
What you are trying to achieve sounds straightforward though. You should be able to avoid most of the complexities of networking (multi-threading, and parallel connections). However, you will need to keep the many failure modes in mind, such as client/server disconnecting mid-transfer.

Have you considered using the server log file as a data source rather than rcon messages?

**Comment by collectVood** [comment]
I actually used ruco especially made for the rust game server. I think it works fine for what I need right now

**Comment by alexkroh** [comment]
Okay. Good luck!
